### ISSUE TITLE
Most buttons in campaign do nothing 

### ISSUE THREAD

**Issue by JPSharp** [SCCapstone/BoredBards#148]
https://user-images.githubusercontent.com/44646798/222790048-c291449c-d418-4413-856f-dbe7bbb821e2.mp4

**Comment by FrozenDrew** [comment]
[device-2023-04-24-134506.webm](https://user-images.githubusercontent.com/77404534/234075558-e32ac722-d76b-4aac-a6dd-8dbe1d339f9d.webm)
