### ISSUE TITLE
NPCs, Enemies, Maps, Players buttons do nothing

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/BoredBards#169]
https://user-images.githubusercontent.com/228704/229815336-2bd7c081-9265-4d69-ac0a-e7beaf720e11.mp4

**Comment by csimons637** [comment]
Changed to the Monsters and Enemies Page, accessible from the the Campaign Menu's Monsters and Enemies button.

https://user-images.githubusercontent.com/83017183/234139357-b2066e51-11c2-4c8f-9613-5f9212638b39.mp4
