### ISSUE TITLE
Combat page does nothing

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/BoredBards#170]
probably because I have no players, because #169 players button does not work...

https://user-images.githubusercontent.com/228704/229816791-1afccde9-da12-49f0-ad63-91443ac5cd53.mp4

**Comment by FrozenDrew** [comment]
![image](https://user-images.githubusercontent.com/77404534/234075130-e2f5f126-5948-49e6-abc8-9a019852d7b9.png)
