### ISSUE TITLE
Can't change username

### ISSUE THREAD

**Issue by JPSharp** [SCCapstone/BoredBards#171]
https://user-images.githubusercontent.com/44646798/230222629-2b3c65fd-b817-4334-b6b8-38e51632aaee.mp4

**Comment by FrozenDrew** [comment]
This has been fixed. The username is pulled from the Register page and displayed correctly now you have to create a new account as this change didn't affect the already existing accounts. This change is currently on my branch of the project and has yet to be pushed to main.
