### ISSUE TITLE
Encyclopedia navigation option does nothing

### ISSUE THREAD

**Issue by jackcarroll160** [SCCapstone/BoredBards#177]
When the encyclopedia button on the bottom navigation bar is clicked, nothing happens. The text is also cut off on my device. My testing device is a Samsung Galaxy S7 for reference. 

https://user-images.githubusercontent.com/77450551/230805507-192c53eb-1aa2-4a97-8164-b88cad4129e9.mp4

**Comment by jacobalpowers** [comment]
Encyclopedia Page is implemented and functional.
