### ISSUE TITLE
No exit from notes

### ISSUE THREAD

**Issue by brianmason2001** [SCCapstone/BoredBards#185]
When creating a note the user cannot decide to stop making a note because there's no exit button.
![image](https://user-images.githubusercontent.com/77559083/231856948-1bf59025-d466-4c92-8b6a-54ab147b1d65.png)

**Comment by FrozenDrew** [comment]
![image](https://user-images.githubusercontent.com/77404534/232374673-7c19170f-dafd-43b6-aeba-a166ec697a0c.png)
