### ISSUE TITLE
About Page Contents

### ISSUE THREAD

**Issue by csimons637** [SCCapstone/BoredBards#194]
Post a short description below (and provide any relevant links: LinkedIn, GitHub, etc.) for the about page of the website.

**Comment by CarolineBarrineau** [comment]
Caroline Barrineau has a Bachelor’s of Computer Science and is passionate about software development, game development, and GUIs. Computer Science allows for the freedom of creativity with a healthy dose of puzzle-solving.

**Comment by FrozenDrew** [comment]
Andrew MacMurray has a Bachelor of Computer Information Systems and a Minor in Business Administration. He is passionate about emerging technologies and how they will affect different markets with a predominate focus on robotics and AI.

**Comment by jacobalpowers** [comment]
Jacob Powers has a Bachelors of Computer Information Systems and a Minor in Business Administration. He is interested in the many facets of software development and wishes to farther his knowledge of the field and the industry as a whole.
