### ISSUE TITLE
UI Desgining of Screens (xml and java use of buttons)

### ISSUE THREAD

**Issue by CarolineBarrineau** [SCCapstone/BoredBards#50]
#### Each Screen is conceptualized in the Archietcure Page and linked here
- [x] [Login Screen](https://github.com/SCCapstone/BoredBards/wiki/Architecture#user-account)
- [x] [Registration Screen](https://github.com/SCCapstone/BoredBards/wiki/Architecture#user-account)
- [x] [Profile Screen]( https://github.com/SCCapstone/BoredBards/wiki/Architecture#profile )
> - [x] to Campaigns
> - [x] to Enemies and Monsters Database Search
- [x] [Main Menu Screen](https://github.com/SCCapstone/BoredBards/wiki/Architecture#menu-screen)
- [x] [Notes Screen](https://github.com/SCCapstone/BoredBards/wiki/Architecture#notes)

- [x] [Name Generator Screen](https://github.com/SCCapstone/BoredBards/wiki/Architecture#name-generator)
- [ ] [Enemies and Monsters Screen](https://github.com/SCCapstone/BoredBards/wiki/Architecture#enemies-and-monsters)

- [x] BoredBard laucher icon
- [x] Campaign icon
- [x] Notes icon
- [x] Settings icon
- [x] Encyclopedia icon
- [x] Roller icon

**Comment by FrozenDrew** [comment]
modified to fit the actual 1.0 release goals.
